name: TestBuildDeploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Gradle
        run: ./gradlew test --info
        env:
          APP_SECRET: 123ABC
  build-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Zip Revision
        uses: papeloto/action-zip@v1
        with:
          files: scripts build/libs/myapp-0.0.1-SNAPSHOT.jar appspec.yml
          dest: latest.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GITHUB_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_SECRET_KEY }}
          aws-region: eu-west-2

      - name: Push Revision to S3
        run: |
          aws s3 --region eu-west-2 cp latest.zip s3://springboot-codedeploy-revisions
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GITHUB_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_SECRET_KEY }}
          aws-region: eu-west-2

      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name SpringBootCodeDeployApplication \
            --deployment-group-name SpringBootCodeDeployDeploymentGroup \
            --s3-location bucket=springboot-codedeploy-revisions,key=latest.zip,bundleType=zip
